### ISSUE TITLE
Get protection group is not retrieving "view_params"

### ISSUE THREAD

**Issue by anusajith** [cohesity/cohesity_sdk#1]
## 🐛 Bug Report
Hey Team,

When we are trying to retrieve a protection group  using v2 client, it is not able to retrieve the "view_params"  in the response as shown below:

{'abort_in_blackouts': False,
 'description': '',
 'environment': 'kView',
 'id': <id>,
 'is_active': True,
 'is_paused': False,
 'missing_entities': None,
 'name': 'Test Views',
 'num_protected_objects': 101,
 'permissions': [],
 'policy_id': <policy_id>,
 'priority': 'kLow',
 'sla': [{'backup_run_type': 'kIncremental', 'sla_minutes': 60},
         {'backup_run_type': 'kFull', 'sla_minutes': 120}],
 'start_time': {'hour': 2, 'minute': 0, 'time_zone': 'Australia/Sydney'},
 'storage_domain_id': <id>}

According to the cohesity-sdk, return type should be :
![image](https://github.com/cohesity/cohesity_sdk/assets/88121157/52aa1e35-31c3-4d33-8e5c-7ba2b50abdc0)

In the model, "view_params" field is present too:

![image](https://github.com/cohesity/cohesity_sdk/assets/88121157/38be0bca-8d3d-4637-8155-6bfea5eb888c)

but that is not returned.

## To Reproduce

1. Run Cohesity_v2_client.protection_group.get_protection_group_by_id(<id>)
2. The response should have "view_params", but is missing.

## Expected behavior
If a protection group of "cohesity view " type, 100+ views in it, how we can retrieve the view_ids or view_names from the protection group?

Additional question:
Please check and confirm , the names of models and wrappers are right. Return types are defined as expected?

**Comment by naveena-maplelabs** [comment]
@anusajith Can you please upgrade to the latest SDK version 1.2.0 https://pypi.org/project/cohesity-sdk/
Issue will be resolved, Please let us know if you face any issues. thanks

**Comment by anusajith** [comment]
By any chance can we get uuid removed from the files / classnames,filenames etc under cohesity-sdk.models like 
![image](https://github.com/cohesity/cohesity_sdk/assets/88121157/6e923fa0-683b-45dc-ac63-e8e38d27b391)


and 

![image](https://github.com/cohesity/cohesity_sdk/assets/88121157/20dd9a1e-d646-4085-8caa-61bc737c908d)

**Comment by naveena-maplelabs** [comment]
Will look into this and remove the unused modules in our next release, thanks.
